### ISSUE TITLE
RESERVED6 is a type of brightness control

### ISSUE THREAD

**Issue by qbancoffee** [shuuryou/imacg3#7]
Playing with RESERVED 6 values I found that the range is from 0xC0  to 0xFF.
Where 0xC0 is the brightest and 0XFF is completely dark. I believe this brightness is
the analog  of the RGB DRIVES so it should be called BRIGHTNESS_DRIVE 
or something like that.

**Comment by shuuryou** [comment]
From my limited knowledge of CRTs, there's:
1. *Screen voltage* (what I kept calling _master brightness_), which is set by the potentiometer on the flyback
1. *User brightness*, which is what it says on the tin, i.e. what users can set
1. _**Secondary brightness**_, a term that I've seen thrown around in some CRT-related patents, but do not fully understand yet.

Currently I'm guessing this might be the third. I don't object the name _BRIGHTNESS_DRIVE_ either though.

I'll add a control for it later this week below the main brightness slider.

It probably makes sense to make it grayed out or hidden unless advanced controls are on. If it's not even in the Apple Display Adjustment Utility (otherwise we'd know about it already since you spent time analyzing what that utility did), it probably wasn't meant to be messed with casually.

**Comment by qbancoffee** [comment]
I was not aware there was a Secondary brightness used for CRTs......
I agree that it isn't for casual use and should be in the advanced menu.
Using it scared me because I thought I killed my IVAD board and/or my CRT!

**Comment by shuuryou** [comment]
It's added now (I forgot to reference this issue in a bunch of commits). Please give it a try when you find the time. If you have advanced controls enabled, you should see a second brightness slider pop up below the user brightness slider.

You may have to adjust your sketch so it accepts the setting change.

Can you tell me the Spanish translation for this:

> brightnessDriveGroupBox.Text | Brightness &Gain 

It's probably easier to just post it here instead of dragging out the translator tool for one change.

I called the slider _Brightness Gain_, since in a bunch of manuals for CRTs the R, G, and B drive controls were also referred to as _Gain_. Not sure which is the best or correct wording, but at least it's consistent across the app.

I also took the chance to change the way advanced controls are laid out (instead of grayed out, they're now hidden if advanced controls are disabled) and this may introduce a host of new visual glitches when running on Mono. If you find anything is weird or controls are missing or misaligned, please let me know and I'll fix it.

**Comment by qbancoffee** [comment]
I'll try and test it later on today and let you know.

"Brightness Gain" should just be "Ganancia de brillo" but who knows since even all of the native spanish speakers I know never have spanish as the OS language, at least not in the united states. 
Most use english terms for computer related things.

That said , I hadn't really thought about what "Brightness Gain" really is so I looked it up.
All of the Gains are really amplification/attenuation of the parameters so they don't directly apply to the image whereas the parameters are used to adjust the image.

So Brightness Gain is used to adjust the Brightness range(maybe) and Brightness
is a relative adjustment riding on Brightness Gain that the user directly manipulates.
  
This means that in Spanish it should then be "Ganancia del brillo"  and therefore
The following should be updated as well.

"Ganancia roja " should be "Ganancia del rojo "
" Ganancia verde" should be "Ganancia del verde "
" Ganancia azul" should be " Ganancia del azul"

This should be pretty easy to edit but if you need me to I'll put in pull request.

**Comment by shuuryou** [comment]
My sketch used 0x40 instead of 0xC0 before and I was getting these weird image smear effects when I turned brightness and contrast all the way up (colors running to the right and turning white). With 0xC0 that no longer happens!
